# Hipocampo — Opciones de Donación

github: [carrasquelalex1]
paypal: https://paypal.me/alexandercarrasquel
custom:
  - https://paypal.me/alexandercarrasquel
  - https://github.com/carrasquelalex1/hipocampo#-donaciones
