# Hipocampo — Opciones de Donación

github: [carrasquelalex1]
paypal: https://paypal.me/carrasquealex
custom:
  - https://paypal.me/carrasquealex
  - https://github.com/carrasquelalex1/hipocampo#-donaciones
