#!/bin/bash
set -e

PG_BIN="/usr/lib/postgresql/${PG_MAJOR}/bin"

init_db() {
    if [ ! -s "$PGDATA/PG_VERSION" ]; then
        echo "Initializing PostgreSQL..."
        mkdir -p "$PGDATA"
        chown -R postgres:postgres "$PGDATA"
        su - postgres -c "${PG_BIN}/initdb -D $PGDATA" 2>&1

        echo "Configuring PostgreSQL..."
        echo "listen_addresses = 'localhost'" >> "$PGDATA/postgresql.conf"
        echo "port = 5432" >> "$PGDATA/postgresql.conf"
        echo "wal_level = minimal" >> "$PGDATA/postgresql.conf"
        echo "fsync = off" >> "$PGDATA/postgresql.conf"
        echo "full_page_writes = off" >> "$PGDATA/postgresql.conf"

        pg_hba="$PGDATA/pg_hba.conf"
        echo "# Generated by entrypoint" > "$pg_hba"
        echo "host all all 127.0.0.1/32 password" >> "$pg_hba"
        echo "host all all ::1/128 password" >> "$pg_hba"
        echo "local all all trust" >> "$pg_hba"
    fi
}

start_db() {
    echo "Starting PostgreSQL..."
    su - postgres -c "${PG_BIN}/pg_ctl -D $PGDATA -l ${PGDATA}/pg.log start" 2>&1
    for i in $(seq 1 15); do
        if su - postgres -c "${PG_BIN}/pg_isready -q" 2>/dev/null; then
            echo "PostgreSQL is ready"
            return 0
        fi
        sleep 1
    done
    echo "PostgreSQL failed to start"
    exit 1
}

create_db() {
    echo "Creating database and user..."
    su - postgres -c "${PG_BIN}/psql -c \"CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';\"" 2>&1 || true
    su - postgres -c "${PG_BIN}/psql -c \"CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};\"" 2>&1 || true
    echo "Installing extensions..."
    su - postgres -c "${PG_BIN}/psql -d ${DB_NAME} -c 'CREATE EXTENSION IF NOT EXISTS vector;'" 2>&1
    su - postgres -c "${PG_BIN}/psql -d ${DB_NAME} -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;'" 2>&1
    echo "Running schema..."
    su - postgres -c "${PG_BIN}/psql -d ${DB_NAME}" < /app/esquema.sql 2>&1 || true
}

init_db
start_db
create_db

echo "Starting MCP server..."
exec "$@"
